#!/bin/bash

#####################################################################################################
#
#	vtspice - Running SPICE simulations on remote servers 
#
#	Author:		nxg-nxg
#	Repository:	https://github.com/nxg-nxg/vtspice.git
#	Date:		2022/11/19
#
#####################################################################################################

## 			Dependency
## - hspice (You can change to other SPICE like ngspice)
## - screen
## - ssh,scp
##
##
## 			Before Using
## This script transfers local files to a remote server via scp 
## and runs the simulation on the remote server with screen 
## virtual terminal. Depending on your machine configuration, 
## you may need to enter a password for the ssh connection. 
## If this is inconvenient, it is recommended to create a 
## special user on remote server who can only execute SPICE 
## commands and use public key authentication without a password.
##
##
## 			Variables
## Username who run simulation on remote server
REMOTEUSR="user1"

## IP adress of remote server
REMOTEIP="192.168.0.100"

## Path of directory for vtspice on remote server (Do not include the / at the end)
REMOTEVTSDIR="/home/remoteuser/vtspice"

## Path to the original file of the SPICE command (Use `which hspice`)
SPICE="/path/to/hspice"

## Options given to SPICE commands
OPTIONS="-mt 8 -hpp"


#####################################################################################################

## Input check
if [ $# == 0 ] || [ $1 == "--help" ] || [ $1 == "-help" ] || [ $1 == "-h" ]
then
        echo "EXAMPLE: vtspice INV.sp netlist mos.mdl mos.skw..."
        echo "USAGE  : vtspice <.sp file> <other files>"
        exit 0
fi


## Request simulation to remote server
if [ $1 != "run" ]
then 
	HEADFILE=$1
	OTHERFILES=${@:2}
	RUNDATE=`date "+%m%d%H%M%S"`
	CELLNAME=${HEADFILE%.*}
	SOCKETNAME="$CELLNAME-$RUNDATE"

	# Files (include this script) is sent to remote server
	mkdir $RUNDATE
	cp $0 $HEADFILE $OTHERFILES $RUNDATE/
	if [ $? != 0 ]
	then 
		echo "ERROR: No such file."
		rm -rf $RUNDATE
		exit 0
	fi

	scp -r $RUNDATE $REMOTEUSR@$REMOTEIP:$REMOTEVTSDIR
	if [ $? != 0 ]
	then 
		echo "ERROR: scp command failed."
		rm -rf $RUNDATE
		exit 0
	fi
	rm -rf $RUNDATE

	# Run vtspice script with virtual terminal
	ssh -t $REMOTEUSR@$REMOTEIP screen -S $SOCKETNAME "sh -c \"cd $REMOTEVTSDIR/$RUNDATE; ./vtspice run $HEADFILE $OTHERFILES $RUNDATE\""

	# Copy result files on remote server to local server
	scp -r $REMOTEUSR@$REMOTEIP:$REMOTEVTSDIR/$RUNDATE/* ./
	if [ $? != 0 ]
	then 
		echo "ERROR: scp command failed."
		echo "ERROR: ssh into the remote server and look at the results file directly."
		exit 0
	fi

	# Remote result files on remote server
	ssh $REMOTEUSR@$REMOTEIP rm -rf $REMOTEVTSDIR/$RUNDATE
	
	echo "FINISHED: vtspice finished successfully!"
fi


## Run simulation on remote server
if [ $1 == "run" ]
then 
	HEADFILE=$2
	OTHERFILES=$3
	RUNDATE=$4
	CELLNAME=${HEADFILE%.*}
	
	# Start simulation
	"$SPICE" $HEADFILE $OPTIONS | tee $CELLNAME.spice.log

	# Remote files watch sent from local server
	rm ./$HEADFILE ./$OTHERFILES $0 -f
fi



